findify/findify-js

- packages/qux/src/index.ts
affects: @findify/qux
A longer description
on multiple lines.
This commit wizard is cool.
> fix(qux): bugfix-1 (testing semantic-releases)

- packages/quuz/src/index.ts
> feat(quuz): add quuz2 function

- packages/quux/src/index.ts
> feat(quux): add aa function (testing semantic releases)

- packages/mjs/src/components.ts
> chore(mjs): add extra space

- packages/mjs/src/features/autocomplete/index.tsx
- packages/mjs/src/features/recommendations/index.tsx
- packages/mjs/src/features/search/index.tsx
- packages/ui-components/src/widgets/Product/index.tsx
> feat(mjs): open new tab on product click if ctrl or cmd button pressed

- packages/mjs/dev/config.js
- packages/mjs/loader/index.js
- packages/mjs/src/helpers/windowEventListener.ts
- packages/mjs/src/states/LocationsState.ts
> chore(mjs): pick commits from old MJS

- packages/mjs/loader/index.js
> chore(mjs): update loader.js to support new paths

- package-lock.json
- packages/mjs/.gitignore
- packages/mjs/tsconfig.json
- packages/ui-components/src/internals/CheckboxBodyFacet/ListRenderer.tsx
> fix(ui-components): hotfix react autosizer mensure width

- package-lock.json
- packages/analytics/package.json
- packages/analytics/src/index.ts
- packages/mjs/package.json
- packages/mjs/src/index.ts
> fix(*): add dataset polyfill for IE9

- .travis/after_success.sh
removes prefixes we added yesterday evening
> chore(^): remove mjs version prefix workaround

- packages/sdk/package.json
> release-2017-10-10-1

- packages/ui-components/src/internals/Image/index.tsx
> fix(ui-components): fix Image component

- jest.config.js
- jest/__mocks__/fileMock.js
- jest/__mocks__/styleMapper.js
- packages/ui-components/src/internals/Button/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui-components/src/internals/Button/index.tsx
- packages/ui-components/src/internals/ExpandButton/__tests__/__snapshots__/index.ts.tsx.snap
- packages/ui-components/src/internals/ExpandButton/__tests__/index.ts.tsx
- packages/ui-components/src/internals/ExpandButton/index.tsx
- packages/ui-components/src/internals/GenericFacet/Raw.tsx
- packages/ui-components/src/internals/GenericFacet/__tests__/Raw.test.tsx
- packages/ui-components/src/internals/GenericFacet/__tests__/__snapshots__/Raw.test.tsx.snap
- packages/ui-components/src/internals/GenericFacet/index.tsx
- packages/ui-components/src/internals/Icon/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui-components/src/internals/Icon/__tests__/index.test.tsx
- packages/ui-components/src/internals/Icon/index.tsx
- packages/ui-components/src/internals/Image/__tests__/index.test.tsx
- packages/ui-components/src/internals/Link/index.ts
- packages/ui-components/src/internals/PoweredBy/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui-components/src/internals/PoweredBy/__tests__/index.test.tsx
- packages/ui-components/src/internals/PoweredBy/index.tsx
- packages/ui-components/src/internals/ProductMatches/index.tsx
- packages/ui-components/src/internals/SearchInput/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui-components/src/internals/SearchInput/__tests__/index.test.tsx
- packages/ui-components/src/internals/SearchInput/index.tsx
- packages/ui-components/src/widgets/Grid/Column.tsx
- packages/ui-components/src/widgets/Grid/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui-components/src/widgets/Grid/__tests__/index.test.tsx
- packages/ui-components/src/widgets/Grid/index.tsx
increases test coverage for ui-components package, adds types
> test(ui-components): add more tests for leaf components

- packages/ui-components/package.json
- packages/ui-components/src/internals/DesktopFacetsList/index.tsx
> fix(ui-components): add a quick fix for facet list rendering performance

- packages/mjs/dev/config.js
- packages/mjs/package.json
- packages/mjs/src/features/search/provider/InstanceMemo.ts
- packages/mjs/src/features/search/provider/index.ts
> fix(mjs): fix duplicate results in mjs infinite scroll

- packages/mjs/src/states/LocationsState.ts
> fix(mjs): fix GA page view tracking

- .lintstagedrc
- packages/mjs/dev/config.js
- packages/ui-components/src/helpers/columnsSize.ts
- packages/ui-components/src/internals/CategoryBodyFacet/index.tsx
- packages/ui-components/src/internals/CategoryBodyFacet/styles.css
- packages/ui-components/src/internals/CheckboxBodyFacet/Checkbox/styles.css
- packages/ui-components/src/internals/CheckboxBodyFacet/Rating/styles.css
- packages/ui-components/src/internals/CheckboxBodyFacet/index.tsx
- packages/ui-components/src/internals/CheckboxBodyFacet/styles.css
- packages/ui-components/src/internals/ColorBodyFacet/index.tsx
- packages/ui-components/src/internals/ColorBodyFacet/styles.css
- packages/ui-components/src/internals/RangeBodyFacet/styles.css
- packages/ui-components/src/layouts/FacetsLayout/index.tsx
- packages/ui-components/src/layouts/ResultsLayout/index.tsx
- packages/ui-components/src/layouts/ResultsLayout/styles.css
- packages/ui-components/src/lists/ProductsList/index.tsx
BREAKING CHANGE:
Columns prop was removed from ResultsLayout
<!--
> feat(ui-components): use facets dynamic width

- packages/mjs/src/features/search/provider/InstanceMemo.ts
- packages/mjs/src/features/search/provider/index.ts
> fix(mjs): fix sorting when infinite scroll is enabled

- packages/mjs/README.md
- packages/ui-components/README.md
> docs(*): update mjs & ui-components READMEs

- packages/mjs/src/features/autocomplete/stylesMapper.ts
> feat(mjs): adjust autocomplete position via config

- packages/ui-components/src/internals/ColorBodyFacet/index.tsx
- packages/ui-components/src/widgets/BreadCrumbs/index.tsx
> fix(mjs): lowercase colors in facet and breadcrumbs

- packages/analytics/src/index.ts
> fix(analytics): do not track events without data-attributes

- packages/mjs/src/features/search/provider/index.ts
> fix(mjs): fix lazyload states compare

- packages/ui-components/src/internals/CheckboxBodyFacet/index.tsx
> fix(ui-components): trigger checkbox update on expand button click

- packages/ui-components/src/internals/CheckboxBodyFacet/index.tsx
> fix(mjs): remove placeholder from size-me in checkboxes

- .travis.yml
Removes git depth from travis CI config
> release-2017-10-17-1

- .travis.yml
> release-2017-10-17-2

- packages/mjs/loader/index.js
> chore(mjs): expose analytics instance to window

- packages/ui-components/src/internals/CategoryBodyFacet/index.tsx
- packages/ui-components/src/internals/CheckboxBodyFacet/index.tsx
- packages/ui-components/src/internals/ColorBodyFacet/index.tsx
- packages/ui-components/src/internals/GenericFacet/index.tsx
> fix(mjs): set size of facet to generic wrapper

- packages/mjs/src/helpers/handleAnalytics.ts
> fix(mjs): send correnct data to shopify

- packages/mjs/src/features/search/provider/InstanceMemo.ts
- packages/mjs/src/features/search/provider/index.ts
> fix(mjs): revert infinite scroll fixes

- packages/ui-components/src/internals/GenericFacet/index.tsx
- packages/ui-components/src/internals/GenericFacet/styles.css
- packages/ui-components/src/layouts/ResultsLayout/styles.css
> fix(mjs): set max width to facets list | remove doubling class names

- packages/ui-components/src/internals/Image/index.tsx
- packages/ui-components/src/widgets/Product/index.tsx
> fix(mjs): move sizeMe to image component

- packages/mjs/src/features/search/provider/helpers.ts
> fix(mjs): remove filtrs from initial state comparator

- packages/ui-components/src/internals/Image/index.tsx
> fix(mjs): hide images lazy load

- packages/mjs/dev/config.js
- packages/mjs/loader/index.js
- packages/mjs/scripts/development.js
- packages/mjs/src/index.ts
- packages/ui-components/src/internals/CategoryBodyFacet/Tree.tsx
- packages/ui-components/src/internals/CategoryBodyFacet/styles.css
> fix(mjs): fix category facet nesting styles | Update mjs loader

- packages/mjs/loader/index.js
> chore(mjs): replace polyfill.io with babel-polyfill

- packages/mjs/loader/index.js
- packages/ui-components/src/layouts/ResultsLayout/styles.css
> fix(mjs): return loosed resuts class name

- packages/mjs/loader/index.js
> fix(mjs): fix loader

- packages/mjs/dev/config.js
- packages/mjs/dev/templates/index.html
- packages/mjs/src/features/search/provider/helpers.ts
- packages/mjs/src/features/search/provider/index.ts
- packages/ui-components/src/internals/GenericFacet/index.tsx
> fix(mjs): fix Lazy Load in Collections and Facets computed width

- packages/ui-components/src/internals/GenericFacet/index.tsx
- packages/ui-components/src/layouts/ResultsLayout/index.tsx
> fix(mjs): remove facets auto sizer

- packages/mjs/src/features/recommendations/index.tsx
- packages/ui-components/src/internals/GenericFacet/index.tsx
- packages/ui-components/src/internals/GenericFacet/styles.css
- packages/ui-components/src/layouts/ResultsLayout/index.tsx
> fix(mjs): return class names in ResultsLayout and GenericFacet

- packages/ui-components/src/layouts/ResultsLayout/index.tsx
> fix(mjs): change products class nesting

- packages/mjs/src/features/autocomplete/stylesMapper.ts
- packages/ui-components/src/internals/CheckboxBodyFacet/Checkbox/styles.css
- packages/ui-components/src/internals/CheckboxBodyFacet/Rating/styles.css
> fix(mjs): fix checkboxes

- packages/mjs/package.json
> chore(mjs): build MJS as library

- packages/mjs/src/features/search/provider/index.ts
Reset product list when query is changed
> fix(mjs): fix infinite scroll (for case when query is changed)

- packages/mjs/.gitignore
- packages/mjs/.npmignore
> fix(mjs): add .npmignore, include missing files in resulting package

- packages/ui-components/src/layouts/ResultsLayout/styles.css
> fix(mjs): fix display of products layout on browsers without flexbox

- packages/ui-components/src/layouts/ResultsLayout/index.tsx
> fix(mjs): change class name for product[s] in results layout

- packages/ui-components/src/layouts/ResultsLayout/styles.css
> fix(mjs): return missed root class

- packages/mjs/package.json
- packages/mjs/scripts/library.js
- packages/mjs/scripts/production.js
- packages/ui-components/scripts/production.js
> chore(mjs): reduce size of MJS|UI-components when build them as lib

- package.json
- packages/mjs/src/features/autocomplete/index.tsx
> fix(mjs): bump version

- packages/analytics/src/helpers/eventsHelpers.ts
> fix(analytics): fix purchase event - include line_items

- packages/mjs/package.json
> fix(mjs): change url to the repo

- packages/ui-components/src/widgets/Sorting/index.tsx
> fix(ui-complonents): bump build

- packages/mjs/package.json
> fix(mjs): update ui version

- packages/mjs/package.json
- packages/mjs/src/decorators/connectProvider.ts
- packages/mjs/src/decorators/loadUIComponents.ts
- packages/mjs/src/decorators/postProcess.ts
- packages/mjs/src/decorators/watchClickOutside.tsx
- packages/mjs/src/decorators/withFakeLocation.ts
- packages/mjs/src/decorators/withFrame.tsx
- packages/mjs/src/decorators/withPortal.tsx
- packages/mjs/src/decorators/withStateOnChange.ts
- packages/mjs/src/decorators/withWrapper.tsx
- packages/mjs/src/helpers/createFeature.ts
- packages/ui-components/package.json
- packages/ui-components/src/helpers/mapTypeToFacet.ts
- packages/ui-components/src/helpers/watchFrameSize.ts
- packages/ui-components/src/helpers/withConfig.ts
- packages/ui-components/src/helpers/withHooks.ts
- packages/ui-components/src/internals/AutocompleteBody/index.tsx
- packages/ui-components/src/internals/AutocompleteMobileBody/index.tsx
- packages/ui-components/src/internals/CategoryBodyFacet/Tree.tsx
- packages/ui-components/src/internals/CheckboxBodyFacet/ListRenderer.tsx
- packages/ui-components/src/internals/ColorBodyFacet/index.tsx
- packages/ui-components/src/internals/DesktopFacetsList/index.tsx
- packages/ui-components/src/internals/MobileFacetsList/index.tsx
- packages/ui-components/src/internals/Stickers/index.tsx
- packages/ui-components/src/layouts/FacetsLayout/index.tsx
- packages/ui-components/src/lists/ProductsList/index.tsx
- packages/ui-components/src/widgets/BreadCrumbs/index.tsx
- packages/ui-components/src/widgets/Grid/Column.tsx
- packages/ui-components/src/widgets/ProductsCarousel/index.tsx
> fix(mjs): update recompose to 0.26.x

- packages/mjs/src/features/autocomplete/mobileWrapper.tsx
- packages/mjs/src/features/autocomplete/stylesMapper.ts
> fix(mjs): fix text blur because of css transform

- packages/ui-components/src/internals/Image/styles.css
> fix(ui-components): hide product image before its loaded

- package.json
- packages/analytics/src/index.ts
- packages/analytics/webpack.config.js
- packages/helpers/webpack.config.js
- packages/mjs/scripts/production.js
- packages/sdk/README.md
- packages/ui-components/scripts/production.js
affects: @findify/analytics, @findify/helpers, @findify/mjs, @findify/sdk, @findify/ui-components
<!--
> fix(mjs, ui-components, analytics): fix build process

- packages/mjs/scripts/production.js
> fix(mjs): fix uglify plugin

- packages/mjs/src/decorators/withFrame.tsx
- packages/mjs/src/features/autocomplete/stylesMapper.ts
> fix(mjs): replace transition with top/left styles for disable blurring

- packages/mjs/src/features/autocomplete/stylesMapper.ts
> feat(mjs): bump

- packages/ui-components/src/widgets/Product/styles.css
> fix(ui-components): hide product image

- packages/ui-components/.babelrc
> chore(ui-components): fix babel dependencies

- packages/sdk/package.json
> test(sdk): run tests on CI

- packages/sdk/README.md
BREAKING CHANGE:
README.md
<!--
> feat(sdk): release sdk 2.0.0

- packages/sdk/package.json
> chore(sdk): build sdk lib right after install

- packages/agent/src/types.ts
- packages/agent/tsconfig.base.json
> chore(agent): fix agent dependecies

- packages/agent/package.json
- packages/agent/src/types.ts
- packages/agent/tsconfig.base.json
affects: @findify/agent
For some reason tests can not resolve sdk path
<!--
> chore(agent): do not run tests for now

- lerna.json
- package.json
- packages/sdk/package.json
> chore(*): prepare packages after bootstrap

- packages/agent/package.json
> chore(agent): bump sdk version

- .travis/after_success.sh
affects: @findify/agent, @findify/sdk
<!--
> chore(agent, sdk): deploy pkgs to s3

- .travis/after_success.sh
- packages/agent/CHANGELOG.md
- packages/analytics-dom/CHANGELOG.md
affects: @findify/agent, @findify/analytics-dom
<!--
> fix(analytics-dom): fix s3 deploy bash

- .travis/after_success.sh
affects: @findify/analytics-dom
<!--
> fix(analytics-dom): add analytics-dom to deployable packages on s3

- packages/analytics/src/modules/request.ts
> feat(analytics): send analitycs via beacon

- packages/react-connect/src/index.ts
affects: @findify/react-connect
<!--
> fix(react-connect): bump version and remove reexports

- packages/react-connect/.npmignore
affects: @findify/react-connect
<!--
> fix(react-connect): add npmignore

- packages/agent/.npmignore
> fix(agent): add npmignore to agent, to publish lib folder

- packages/analytics-dom/.npmignore
- packages/sdk/.npmignore
affects: @findify/analytics-dom, @findify/sdk
<!--
> fix(sdk): add npmignore to sdk and analytics-dom

- packages/react-connect/src/connect/connectBreadcrumbs.ts
- packages/react-connect/src/connect/connectFacets.ts
- packages/react-connect/src/connect/connectItems.ts
- packages/react-connect/src/immutable/facets.ts
- packages/react-connect/src/immutable/filters.ts
- packages/react-connect/src/immutable/item.ts
> Release 13-02-2018

- packages/mjs/scripts/index.js
> fix(mjs): remove aliases, it breakes the build

- packages/mjs/scripts/index.js
> fix(mjs): remove aliases

- packages/mjs/scripts/index.js
Completly remove webpack aliases
<!--
> Release 22-02-2018(2)

- packages/ui-components/src/internals/StickyFilters/index.tsx
> fix(mjs, ui-components): store offset in the cache

- packages/mjs/scripts/index.js
- packages/ui-components/src/internals/StickyFilters/index.tsx
> Release 23-02-2018

- packages/ui-components/src/internals/StickyFilters/index.tsx
> fix(ui-components): fix height of component and remove extra debounce

- packages/ui-components/src/internals/StickyFilters/index.tsx
Small fixes for sticky filters
> Release 28-02-2018

- packages/ui-components/src/internals/StickyFilters/index.tsx
> fix(mjs, ui-components): remove absolute position from sticky filters

- packages/analytics-dom/package.json
- packages/helpers/.npmignore
affects: @findify/analytics-dom, @findify/helpers, @findify/mjs
<!--
> fix(mjs, helpers, analytics-dom): bump version

- packages/mjs/src/index.ts
> fix(mjs): bump

- packages/mjs/scripts/production.js
> fix(mjs): minify bundle

- packages/mjs/src/features/search/stylesMapper.ts
- packages/ui-components/src/internals/StickyFilters/index.tsx
- packages/ui-components/src/internals/StickyFilters/styles.css
> fix(mjs, ui-components): set fixed position to sticky filters

- packages/ui-components/src/internals/StickyFilters/index.tsx
> fix(ui-components): fix styles dublicated import

- packages/ui-components/src/internals/StickyFilters/index.tsx
- packages/ui-components/src/internals/StickyFilters/styles.css
> fix(ui-components): make sticky filters smarter

- packages/ui-components/scripts/index.js
> fix(ui-components): change loaders order

- packages/bundle/src/helpers/resolveCallback.ts
> fix(bundle): bump version

- .travis/before_install.sh
> chore(*): deploy to s3 for staging

- package.json
> chore(*): prepare modules before last build

- package.json
- packages/react-components/package.json
> chore(react-components): change dependencie version

- .travis/after_success.sh
> chore: update travis build flow

- .travis/after_success.sh
> chore: force publish changes to github

- .travis.yml
- .travis/after_success.sh
> chore: update travis to build only master/development

- lerna.json
- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/analytics-dom/CHANGELOG.md
- packages/analytics-dom/package.json
- packages/analytics/CHANGELOG.md
- packages/analytics/package.json
- packages/bundle/CHANGELOG.md
- packages/bundle/package.json
- packages/processors/CHANGELOG.md
- packages/processors/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/react-connect/CHANGELOG.md
- packages/react-connect/package.json
- packages/react-connect/src/provider/createProvider.ts
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
> Master [ci skip]

- packages/analytics/src/index.ts
ISSUES CLOSED: #MERCHANT-JS-V6-2K
<!--
> fix(analytics): fix analytics initial state values

- packages/react-components/index.d.ts
- packages/react-components/package.json
- packages/react-components/scripts/postcssWrap.js
- packages/react-components/scripts/processCss.js
- packages/react-components/src/components/common/Drawer/view.tsx
- packages/react-components/src/components/search/Query/view.tsx
- yarn.lock
> fix(react-components): increase deep of css styles to avoid overwriting

- packages/react-components/src/components/search/Query/view.tsx
> fix(react-components): change number of partial matched results

- packages/react-components/src/components/search/Query/view.tsx
> fix(react-components): fix null value in query template

- packages/react-components/src/components/common/Image/__snapshots__/test.tsx.snap
- packages/react-components/src/components/common/Image/index.tsx
- packages/react-components/src/components/common/Image/test.tsx
> WIP(react-components): fix bad request while recommendation is loading

- packages/react-components/src/components/CheckboxFacet/styles.css
- packages/react-components/src/components/CheckboxFacet/view.tsx
- packages/react-components/src/components/Facet/view.tsx
- packages/react-components/src/components/search/MobileFacets/styles.css
- packages/react-components/src/components/search/MobileFacets/view.tsx
> fix(react-components): fix checkbox facet not displaying items on ios 10

- packages/analytics/src/modules/storage.ts
- packages/bundle/webpack.config.ts
- packages/react-components/src/components/search/Query/view.tsx
- packages/react-components/src/layouts/Autocomplete/index.tsx
- packages/react-components/src/layouts/Autocomplete/withAutocompleteLogic.ts
- packages/react-components/src/layouts/ContentSearch/index.ts
- packages/react-components/src/layouts/Recommendation/index.ts
- packages/react-components/src/layouts/Search/index.tsx
- packages/react-connect/src/provider/createProvider.ts
- yarn.lock
> Release 19-07-2018(2)

- packages/agent/src/core/Agent.ts
- packages/agent/src/core/Cache.ts
- packages/agent/src/index.ts
- packages/agent/src/utils/format.ts
- packages/react-connect/src/connect/connectBanner.ts
- packages/react-connect/src/connect/connectBreadcrumbs.ts
- packages/react-connect/src/connect/connectConfig.ts
- packages/react-connect/src/connect/connectFacets.ts
- packages/react-connect/src/connect/connectItems.ts
- packages/react-connect/src/connect/connectPagination.ts
- packages/react-connect/src/connect/connectQuery.ts
- packages/react-connect/src/connect/connectSort.ts
- packages/react-connect/src/connect/connectSuggestions.ts
- packages/react-connect/src/connect/createConnect.ts
- packages/react-connect/src/provider/createProvider.ts
affects: @findify/agent, @findify/react-connect
<!--
> docs(agent,react-connect): update docs to clarify architecture

- packages/react-components/src/layouts/Autocomplete/Sidebar/view.tsx
> fix(react-components): fix Sidebar autocomplete not submitting entered query

- packages/react-components/src/helpers/withLazy.tsx
> fix(react-components): apply lazyLoadCount config property to withLazy

- packages/react-connect/src/connect/connectSuggestions.ts
affects: @findify/react-connect
<!--
> fix(react-connect): fix incorrect event name when click on suggestion

- packages/bundle/src/features/recommendation/payload.ts
> fix(bundle): fix incorrect filters field in recommendations

- packages/bundle/package.json
- packages/bundle/scripts/webpackHashPlugin.js
- packages/react-components/src/layouts/Autocomplete/index.tsx
- packages/react-components/src/layouts/Recommendation/index.ts
- packages/react-components/src/layouts/Search/index.tsx
> fix(react-components): return hmr import

- packages/analytics-dom/src/bindings/filters.ts
- packages/bundle/package.json
- packages/bundle/scripts/webpackHashPlugin.js
- packages/react-components/src/components/Banner/view.tsx
- packages/react-components/src/layouts/Autocomplete/index.tsx
- packages/react-components/src/layouts/Recommendation/index.ts
- packages/react-components/src/layouts/Search/index.tsx
> Release 24-07-2018

- packages/agent/package.json
- packages/bundle/package.json
- packages/bundle/src/config.ts
- packages/react-components/src/components/Cards/Product/view.tsx
- packages/react-components/src/components/common/Image/index.tsx
affects: @findify/agent, @findify/bundle, @findify/react-components
<!--
> fix(react-components): minor fixes

- packages/analytics-dom/package.json
affects: @findify/analytics-dom
<!--
> chore(analytics-dom): bump version

- packages/bundle/src/config.ts
- packages/react-components/src/components/search/DesktopActions/view.tsx
- packages/react-components/src/components/search/DesktopFacets/Title.tsx
> fix(bundle,react-components): add localized strings for showing & hiding facets

- packages/react-components/src/components/Cards/Product/Stickers/index.tsx
- packages/react-components/src/components/Cards/Product/view.tsx
- packages/react-components/src/helpers/withColumns.ts
- yarn.lock
> fix(react-components): fix discount sticker rendering

- .babelrc
- packages/analytics-dom/src/bindings/events.ts
- packages/bundle/package.json
- packages/bundle/scripts/dll.js
- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
- packages/react-components/src/components/Cards/Product/view.tsx
- packages/react-components/src/components/CheckboxFacet/view.tsx
- packages/react-components/src/index.ts
- packages/react-connect/src/connect/connectSuggestions.ts
- packages/react-connect/src/immutable/facets.ts
- yarn.lock
> Release 30-07-2018

- packages/bundle/src/index.ts
> chore(bundle): bump version

- packages/bundle/package.json
- packages/bundle/src/index.ts
- yarn.lock
> Version bump

- .babelrc
- packages/bundle/webpack.config.ts
> feat(bundle): use commonjs modules

- packages/bundle/src/config.ts
- packages/react-connect/src/immutable/facets.ts
affects: @findify/bundle, @findify/react-connect
<!--
> fix(react-connect): fix incorrect category filters update

- packages/react-components/src/components/RangeFacet/index.ts
- packages/react-components/src/components/RangeFacet/view.tsx
> fix(react-components): fix range facet not updating values

- packages/react-components/src/components/common/Image/__snapshots__/test.tsx.snap
- packages/react-components/src/components/common/Image/index.tsx
- packages/react-components/src/components/common/Image/test.tsx
> test(react-components): add unit tests for Image to cover lazyload

- packages/bundle/src/features/recommendation/index.ts
> fix(bundle): option to disable initial reqest in recommendations

- packages/bundle/src/features/recommendation/index.ts
- packages/react-components/src/components/RangeFacet/index.ts
> Release 14-08-2018(bundles fix)

- packages/bundle/index.html
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/helpers/log.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> fix(bundle): fix incorrect custom widget key

- packages/bundle/index.html
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/helpers/log.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> Release 17-08-2018

- packages/react-components/src/components/CheckboxFacet/index.ts
- packages/react-components/src/components/autocomplete/SuggestionItem/view.tsx
> fix(react-components): fix regexp unescaped symbols crashing search

- packages/bundle/src/helpers/scrollTo.ts
> fix(bundle): check for not is exist on page in scrollTo

- packages/react-components/src/components/RangeFacet/index.ts
> fix(react-components): set min/max values to rage facet

- packages/bundle/src/helpers/scrollTo.ts
- packages/react-components/src/components/RangeFacet/index.ts
> Release 29-08-2018

- packages/bundle/src/initialize.ts
- packages/react-components/src/components/RangeFacet/index.ts
- packages/react-components/src/components/RangeFacet/view.tsx
> Release 7-09-2018

- packages/react-components/src/components/search/MobileFacets/Titles.tsx
- packages/react-components/src/components/search/MobileFacets/styles.css
> feat(react-components): add displaying of selected categories on mobile facet landing

- packages/bundle/webpack.config.ts
> fix(bundle, build): fix Lodash scope pollution caused by Webpack's AMD parsing

- packages/bundle/src/initialize.ts
> fix(bundle): allow to inject raw functions in components

- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
> Release 09-03-2018

- packages/bundle/src/initialize.ts
> Release 09-03-2018(2)

- packages/bundle/src/initialize.ts
> fix(bundle): console log components cache state

- packages/bundle/src/initialize.ts
> Release/debug 

- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> fix(bundle): prevent scripts loading for initialized findify

- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> Release - probably fix of IOS11 scripts context

- packages/bundle/src/config.ts
- packages/react-components/src/layouts/Recommendation/Slider/view.tsx
> fix(react-components): fix window scroll issue in react-slick

- packages/react-components/src/layouts/Recommendation/Swiper/index.ts
- packages/react-connect/package-lock.json
- packages/react-connect/package.json
- packages/react-connect/src/connect/createConnect.ts
- packages/react-connect/src/provider/createProvider.ts
affects: @findify/react-components, @findify/react-connect
<!--
> feat(react-connect): migrate to new React Context API

- packages/bundle/src/core/render.ts
- packages/bundle/src/features/create.ts
- packages/bundle/src/features/recommendation/payload.ts
- packages/react-components/src/components/CheckboxFacet/index.ts
- packages/react-components/src/components/autocomplete/SuggestionItem/view.tsx
- packages/react-components/src/helpers/escapeRegExp.ts
> fix(bundle, react-components): replace Lodash with simple functions

- packages/bundle/package-lock.json
- packages/bundle/package.json
- packages/bundle/src/index.ts
> fix(bundle): replace Raven with Sentry sdk

- packages/bundle/src/index.ts
> fix(bundle): rollback polyfill

- packages/bundle/index.html
- packages/bundle/src/features/content/index.ts
- packages/react-components/src/components/Cards/Content/styles.css
- packages/react-components/src/components/Cards/Content/view.tsx
- packages/react-components/src/components/Icon/icons/ExternalLink.svg
- packages/react-components/src/components/Icon/index.ts
- packages/react-components/src/components/search/LazyResults/view.tsx
- packages/react-components/src/layouts/Content/view.tsx
> fix(react-components): update Content card

- packages/react-components/src/components/CategoryFacet/view.tsx
- packages/react-components/src/layouts/Autocomplete/Dropdown/trackPosition.ts
> fix(react-components): fix IE autocomplete position

- packages/bundle/src/config.ts
- packages/react-components/src/components/Cards/Product/Stickers/index.tsx
- packages/react-components/src/components/Cards/Product/Stickers/styles.css
> fix(oos-sticker): add translations to oos sticker

- packages/react-components/src/components/RangeFacet/styles.css
> fix(react-components): fix IE11 range facet input width

- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
> feat(bundle): update devtools initialization process

- packages/bundle/src/initialize.ts
> fix(bundle): fix unnecessary config import

- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
> Release 16.01.2019(fix)

- packages/bundle/src/config.ts
- packages/react-components/index.d.ts
- packages/react-connect/src/connect/createConnect.ts
affects: @findify/bundle, @findify/react-components, @findify/react-connect
<!--
> fix(react-connect): fix provider nesting to overwrite top-lvl agent

- packages/bundle/src/features/smart-collection/index.ts
> fix(bundle): add redicrect to sc feature

- packages/bundle/package.json
- yarn.lock
> fix(bundle): update sentry version

- packages/react-components/src/components/Cards/Product/Stickers/index.tsx
- packages/react-components/src/components/Cards/Product/Stickers/styles.css
> fix(react-components): fix oos sticket styles and value

- packages/bundle/package.json
- yarn.lock
> Release 31-01-2019

- packages/bundle/src/config.ts
- packages/react-components/package-lock.json
- packages/react-components/package.json
- packages/react-components/src/components/Cards/Product/__snapshots__/test.tsx.snap
- packages/react-components/src/components/Cards/Product/test.tsx
- packages/react-components/src/components/Cards/Product/view.tsx
- packages/react-components/src/components/RangeFacet/content.tsx
- packages/react-components/src/helpers/formatCurrency.ts
> fix(react-components): use accounting.js to format currency

- packages/bundle/src/initialize.ts
> fix(bundle): fallback currency

- packages/bundle/src/initialize.ts
> Release 14-03-2019

- packages/react-components/index.d.ts
- packages/react-connect/src/immutable/facets.ts
- packages/react-connect/src/utils/debounce.ts
affects: @findify/react-components, @findify/react-connect
<!--
> fix(react-connect): added debounce to facet item toggle method

- packages/react-connect/src/immutable/facets.ts
affects: @findify/react-connect
<!--
> fix(react-connect): removed uncecessary logs

- packages/bundle/src/initialize.ts
- packages/react-components/index.d.ts
- packages/react-connect/src/immutable/facets.ts
- packages/react-connect/src/utils/debounce.ts
> Release 01-04-2019

- packages/bundle/src/index.ts
> fix(bundle): fixed release

- packages/bundle/src/index.ts
- packages/react-components/index.d.ts
- yarn.lock
> fix(bundle): probably fix wrong import issue

- packages/bundle/src/index.ts
- packages/react-components/index.d.ts
- yarn.lock
> Release 04-04-2019(2)

- packages/bundle/src/index.ts
> fix(bundle): fix the uglified version of dependencies import

- packages/bundle/package.json
> fix(bundle): fix sentry version

- packages/bundle/src/features/autocomplete/index.ts
- packages/react-components/index.d.ts
- packages/react-components/src/layouts/Autocomplete/Sidebar/view.tsx
- packages/react-components/src/layouts/Recommendation/Slider/styles.global.css
- yarn.lock
> fix(bundle, react-components): fix double render of sidebar autocomplete

- packages/analytics/src/settings.ts
> fix(analytics): fix incorrect bigcommerce url

- packages/bundle/webpack.config.ts
> fix(bundle): fix path to react-spring

- packages/analytics/src/settings.ts
- packages/bundle/webpack.config.ts
> Release 19.07.2019(fix)

- packages/bundle/webpack.config.ts
- packages/react-components/src/components/common/Image/index.tsx
> Release 15-07-2019

- packages/bundle/src/core/location.ts
> fix(bundle): removed history object from public access

- packages/bundle/src/core/location.ts
- packages/react-components/src/components/common/Image/index.tsx
> Release 16/07/2019

- .travis.yml
> chore: update travis node version

- .travis.yml
> Release 17.07.2019(Bump version)

- lerna.json
> fix(bundle): ignore changes in d.ts

- lerna.json
- packages/bundle/src/index.ts
> Release 17.07.2019(bump)

- lerna.json
- package.json
- yarn.lock
> fix: change lerna version

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): fix prefetch url

- packages/bundle/webpack.config.ts
> fix(bundle): change publicPath

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): change public path on the fly

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> Release 18.07.2019(fix)

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): user RAW version

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> Release 18.07.1988(fix components prefetch)

- packages/bundle/scripts/dll.js
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
> fix(bundle): split polyfills

- packages/bundle/scripts/dll.js
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
> Release 18.07.2019(split polyfill)

- .babelrc
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
> fix(bundle): test code spiting

- .babelrc
- packages/bundle/scripts/dll.js
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
> Release 19.07.2019(test split)

- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
> fix(bundle): improve code spliting

- .babelrc
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/helpers/renderLazyComponent.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
- packages/bundle/src/polyfill.ts
> fix(bundle): fix autocomplete rerender

- packages/bundle/src/index.ts
> fix(bundle): load autocomplete from beginning

- packages/bundle/src/core/location.ts
- packages/bundle/src/initialize.ts
> fix(bundle): fix history module cache prune if customizations presents

- packages/bundle/src/core/location.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> Release 24.07.2019

- packages/bundle/webpack.config.ts
> fix(bundle): disable concatenation for modules to support customizations

- packages/bundle/webpack.config.ts
> fix(bundle): do not mangle exports names

- packages/bundle/webpack.config.ts
> Release 25-07-2019(fix)

- packages/bundle/webpack.config.ts
> fix(bundle): import recompose as cjs module

- packages/bundle/webpack.config.ts
- packages/react-components/src/components/Banner/index.ts
> fix(bundle, react-components): prevent module export names to be mangled

- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
> fix(bundle): fix regeneratorRuntime

- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
- packages/react-components/src/components/Banner/index.ts
> Release 25-07-2019(fix regenerator)

- packages/bundle/src/index.ts
> fix(bundle): prefetch components

- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
> fix(bundle): remove prefetch

- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
> Release 26-07-2019

- packages/bundle/src/core/location.ts
- packages/react-components/index.d.ts
- packages/react-connect/package.json
- yarn.lock
affects: @findify/bundle, @findify/react-components, @findify/react-connect
<!--
> fix(bundle): change history to location to check if its search page

- packages/bundle/src/core/location.ts
- packages/bundle/src/core/widgets.ts
- packages/react-components/index.d.ts
- packages/react-connect/package.json
- yarn.lock
> Release 13.08.2019

- packages/sdk/src/api.ts
- packages/sdk/src/client/Client.ts
- packages/sdk/src/utils.ts
- yarn.lock
> fix(sdk): fix nanoid import

- lerna.json
> fix(bundle): ignore cli package by lerna

- lerna.json
- packages/bundle/src/index.ts
> Release 28.08.2019(4)

- packages/cli/package.json
> fix(cli): fix cli prefix

- lerna.json
- packages/cli/package.json
> Release 28.08.2019(5)

- packages/sdk/src/client/Client.ts
> fix(sdk): fix latestRequestID getter in sdk

- packages/cli/package.json
- packages/sdk/src/client/Client.ts
> Release 28.08.2019(6)

- packages/react-components/src/components/common/Image/index.tsx
> fix(react-components): change image size based on width of container

- packages/react-components/src/components/common/Image/index.tsx
- packages/sdk/src/client/Client.ts
> Release 30.08.2019

- packages/react-components/index.d.ts
- packages/react-components/src/components/search/LazyResults/index.ts
> docs(react-components): updated withColumns usage comments

- packages/agent/README.md
- packages/analytics-dom/README.md
- packages/analytics/README.md
- packages/bundle/README.md
- packages/cli/README.md
- packages/react-components/README.md
- packages/react-connect/README.md
affects: @findify/agent, @findify/analytics, @findify/analytics-dom, @findify/bundle, @findify/cli,
@findify/react-components, @findify/react-connect
<!--
> chore(*): update packages description

- README.md
> chore(*): update root README.md

- README.md
> chore: remove emoji, add logo

- packages/react-components/src/layouts/Autocomplete/Dropdown/view.tsx
- packages/react-components/src/layouts/Autocomplete/Fullscreen/index.ts
- packages/react-components/src/layouts/Autocomplete/withAutocompleteLogic.ts
- packages/react-connect/src/connect/createConnect.ts
affects: @findify/react-components, @findify/react-connect
<!--
> fix(react-components, react-connect): update autocomplete logic

- packages/bundle/src/core/widgets.ts
> fix(bundle): add bility to send POST request

- packages/bundle/index.html
- packages/bundle/src/features/autocomplete/index.ts
> fix(bundle): single autocomplete agent

- packages/bundle/index.html
- packages/bundle/package.json
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/features/create.ts
- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
- yarn.lock
> feat(bundle): async react render

- packages/bundle/index.html
- packages/bundle/package.json
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/create.ts
- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
- yarn.lock
> Release 26-09-2019

- packages/bundle/index.html
- packages/bundle/src/features/autocomplete/handlers.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
- packages/react-components/src/layouts/Autocomplete/Dropdown/trackPosition.ts
> fix(bundle): prevent autocomplete position check before document ready

- packages/bundle/src/features/autocomplete/handlers.ts
> fix(bundle): listen for autocomplete form submit after dom ready

- packages/bundle/src/features/autocomplete/handlers.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/index.ts
> fix(bundle): fix second initialization on error

- packages/bundle/src/features/autocomplete/handlers.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/index.ts
> Release 30-09-2019(3)

- packages/bundle/webpack.config.ts
> fix(bundle): change limit of requests and hash normal chunks

- packages/bundle/webpack.config.ts
> fix(bundle): remove chunk hash

- packages/bundle/webpack.config.ts
> Release 01-10-2019(2)

- packages/bundle/scripts/webpackHashPlugin.js
- packages/bundle/src/index.ts
> fix(bundle): prefetch all modules before initialization

- packages/bundle/scripts/webpackHashPlugin.js
- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> Release 04-10-2019

- packages/react-components/index.d.ts
> fix(react-components): bump version

- packages/react-components/src/layouts/Recommendation/index.ts
> fix(react-components): rollback Swiper

- packages/bundle/src/core/render.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/create.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- yarn.lock
> fix(bundle): request data before dom ready, but render protalf after

- packages/bundle/src/core/render.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/create.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- packages/react-components/src/layouts/Recommendation/index.ts
- yarn.lock
> Release 09-10-2019

- packages/bundle/src/features/create.ts
> fix(bundle): fix widgets invalidate

- packages/bundle/src/helpers/resolveCallback.ts
- packages/bundle/src/initialize.ts
> fix(bundle): move findifyCallbacks after dom ready

- packages/bundle/src/features/create.ts
- packages/bundle/src/helpers/resolveCallback.ts
- packages/bundle/src/initialize.ts
> Release 09-10-2019(3)

- .travis.yml
> fix: bump node version

- .travis/before_install.sh
> fix: update travis config

- .travis.yml
- .travis/before_install.sh
> Release 09-10-2019(fix build)

- packages/bundle/src/helpers/resolveCallback.ts
> fix(bundle): fix callback creator

- .travis/before_install.sh
- packages/bundle/src/helpers/resolveCallback.ts
> Release 09-10-2019(5)

- packages/bundle/src/features/content/index.ts
> feat(bundle): allow to pass sorting to the content widgets

- packages/bundle/src/features/content/index.ts
- packages/bundle/src/helpers/resolveCallback.ts
> Release 15.10.2019

- packages/bundle/src/core/location.ts
- packages/bundle/src/features/autocomplete/handlers.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/react-connect/src/connect/connectSuggestions.ts
affects: @findify/bundle, @findify/react-connect
<!--
> feat(bundle, react-connect): added redirect feature to the autocomplete

- .babelrc
> fix(bundle): compile node modules to avoid error in IE

- packages/bundle/webpack.config.ts
> fix(bundle): fix symbol polifyll

- packages/bundle/webpack.config.ts
> fix(bundle): fix promise import

- packages/bundle/webpack.config.ts
> Release 5-11-2019(3)

- babel.config.js
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
- packages/react-components/index.d.ts
> fix(bundle): fix IE Promise

- babel.config.js
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
- packages/react-components/index.d.ts
> Release 6-11-2019

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): disable double initialization

- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
> fix(bundle): fix regenerator runtime import

- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
> Release 6-11-2019(3)

- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/helpers/isNumeric.ts
> fix(bundle): fix scroll if no option present in config

- packages/analytics/src/index.ts
> fix(analytics): bump version

- packages/analytics/.npmignore
> fix(analytics): return dist to npm

- packages/analytics/.npmignore
- packages/analytics/src/index.ts
> Release 18.11.2019(2)

- packages/analytics/.npmignore
- packages/bundle/src/helpers/resolveCallback.ts
- packages/react-components/src/components/RangeFacet/index.ts
- packages/react-components/src/components/RangeFacet/view.tsx
- packages/react-components/src/helpers/formatCurrency.ts
> Release 25.11.2019

- packages/react-components/babel.config.js
> fix(react-components): fix mission styles because of new babel

- packages/react-components/src/layouts/Recommendation/Slider/styles.css
> fix(react-components): fix missed swiper styles

- packages/react-components/babel.config.js
- packages/react-components/src/layouts/Recommendation/Slider/styles.css
> Release 16.12.2019

- packages/cli/test/environment.js
- packages/cli/test/index.js
> chore(cli): update test suite

- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/recommendation/payload.ts
> Add ability to pass rec rules via root node data attributes

- packages/react-components/src/layouts/Recommendation/Slider/Swiper.tsx
> fix(react-components): fix swiper scroll callback

- packages/agent/src/core/Agent.ts
- packages/bundle/index.html
- packages/bundle/src/features/smart-collection/index.ts
- packages/react-components/src/layouts/Recommendation/Slider/Swiper.tsx
- packages/react-connect/src/provider/createProvider.ts
> Release 10.03.2020

- packages/bundle/src/index.ts
> fix(bundle): update sentry url

- packages/bundle/src/index.ts
> Release 17.03.2020[sentry test]

- packages/bundle/src/config.ts
- packages/bundle/src/global.d.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> fix(bundle): try to catch customization exaption

- packages/bundle/src/index.ts
> fix(bundle): release Sentry

- packages/bundle/index.html
- packages/bundle/src/features/autocomplete/handlers.ts
- packages/react-components/src/components/common/MapArray/index.tsx
- packages/react-components/src/components/search/MobileActions/styles.css
> fix(bundle, react-components): minor updates

- packages/react-components/src/components/autocomplete/ProductMatches/styles.css
> fix(react-components): fix product image size in autocomplete

- packages/react-components/src/components/autocomplete/ProductMatches/styles.css
> fix(react-components): fix missed style

- packages/react-components/src/components/autocomplete/ProductMatches/styles.css
> Release 23.03.2020[minor style fixes]

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
> fix(bundle): change config props for scroll

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/react-components/src/components/autocomplete/ProductMatches/styles.css
> Release 02.04.2020

- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
> fix(bundle): throw Error for disabled sentry users, showFallback fix

- packages/react-components/src/components/Cards/Content/styles.css
- packages/react-components/src/components/Dropdown/styles.css
- packages/react-components/src/components/Facet/styles.css
> fix(react-components): fix missed styles variables

- packages/cli/package.json
- packages/cli/test/environment.js
- packages/cli/test/helpers.js
- packages/cli/test/index.js
- packages/cli/test/tests.js
> chore(cli): fix widget detach issue in new MJS version

- packages/bundle/src/features/autocomplete/handlers.ts
> fix(bundle): add debounce to autocomplete

- packages/analytics-dom/src/index.ts
- packages/bundle/index.html
- packages/bundle/src/initialize.ts
> Release 19.05.2020

- packages/react-components/src/components/ColorFacet/content.tsx
> fix(react-components): add color title to color ball

- .travis/after_success.sh
- .travis/before_install.sh
> chore: provide env variables before build

- .travis/after_success.sh
> chore: syntax error

- packages/bundle/src/helpers/observeDomNodes.ts
- packages/bundle/src/initialize.ts
Add observer to watch widget NODE create/remove and automatically attach widgets
<!--
> fix(bundle): observe dom to catch new widgets

- packages/react-components/src/components/CheckboxFacet/Item.tsx
- packages/react-components/src/components/ColorFacet/Item.tsx
- packages/react-components/src/components/RangeFacet/Item.tsx
- packages/react-components/src/components/RatingFacet/Item.tsx
> fix(react-components): add area-selected to checkbox facets

- packages/bundle/src/index.ts
> fix(bundle): hot fix to support crypto in IE

- packages/react-components/src/layouts/Autocomplete/index.tsx
> fix(react-components): fix autocomplete breakpoint

- packages/react-components/src/components/autocomplete/SuggestionItem/styles.css
> fix(react-components): changes suggestion items to be capitalized

- packages/react-components/src/components/RangeFacet/styles.css
> fix(react-components): adds styling to center the divider for RangeFacet

- packages/bundle/src/core/location.ts
- packages/bundle/src/initialize.ts
> Release 20.01.2021(2)

- packages/bundle/src/core/location.ts
> fix(bundle): try to isolate location

- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
> fix(bundle): reduce amount of chunks by merging search and autocomplete

- packages/bundle/src/core/location.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/index.ts
> Release 21.01.2021

- packages/bundle/src/core/location.ts
- packages/bundle/src/initialize.ts
Bundle will always use it own history, but in case you need to use custom - subscribe to updates
<!--
> fix(bundle): revert history changes

- packages/bundle/src/core/location.ts
> fix(bundle): export history

- packages/bundle/src/core/location.ts
- packages/bundle/src/initialize.ts
> fix(bundle): roll back history

- packages/bundle/index.html
- packages/bundle/scripts/webpackHashPlugin.js
- packages/bundle/src/core/events.ts
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- packages/bundle/src/helpers/fallbackNode.ts
- packages/bundle/src/helpers/resolveCallback.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
> fix(bundle): send collection and search requests as fast as possible

- packages/bundle/index.html
- packages/bundle/scripts/webpackHashPlugin.js
- packages/bundle/src/core/events.ts
- packages/bundle/src/core/location.ts
- packages/bundle/src/core/render.ts
- packages/bundle/src/core/widgets.ts
- packages/bundle/src/features/autocomplete/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/features/tabs/index.ts
- packages/bundle/src/helpers/fallbackNode.ts
- packages/bundle/src/helpers/resolveCallback.ts
- packages/bundle/src/index.ts
- packages/bundle/src/initialize.ts
- packages/bundle/webpack.config.ts
> Release 02.02.2020

- packages/bundle/src/core/widgets.ts
> fix(bundle): return request method selector

- packages/bundle/index.html
- packages/react-components/src/components/Button/styles.css
- packages/react-components/src/components/Button/view.tsx
- packages/react-components/src/components/Pagination/view.tsx
> fix(bundle, react-components): change component of pagination button

- packages/bundle/src/config.ts
- packages/bundle/src/core/location.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/react-components/src/components/Pagination/view.tsx
> fix(bundle, react-components): keep non-whitelisted url params in url

- packages/bundle/src/features/search/index.ts
- packages/react-components/index.d.ts
> fix(bundle): disable seroresults by config

- babel.config.js
- package.json
- packages/agent/package.json
- packages/analytics/package.json
- packages/bundle/.babelrc
- packages/bundle/package.json
- packages/bundle/src/core/render.ts
- packages/bundle/src/index.ts
- packages/bundle/src/polyfill.ts
- packages/bundle/webpack.config.ts
- packages/processors/package.json
- packages/sdk/package.json
- yarn.lock
affects: @findify/agent, @findify/analytics, @findify/bundle, @findify/processors, @findify/sdk
<!--
> fix(bundle): optimize build

- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): return node_modules compilations

- babel.config.js
- packages/bundle/webpack.config.ts
> fix(bundle): fix issue with node_modules compilation

- babel.config.js
- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> Release 07.02.2021

- packages/bundle/.npmignore
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> fix(bundle): initially load polyfill if required

- babel.config.js
- packages/bundle/.npmignore
- packages/bundle/package.json
- packages/bundle/src/index.ts
- packages/bundle/webpack.config.ts
> Release 09.02.2020

- packages/bundle/src/features/search/index.ts
> feat(bundle): disable zero results by flag

- packages/react-components/index.d.ts
- packages/react-connect/package.json
- packages/react-connect/src/immutable/createRecord.ts
- packages/react-connect/src/provider/createProvider.ts
- packages/react-connect/tsconfig.lib.json
affects: @findify/react-components, @findify/react-connect
<!--
> chore(react-connect): move react to peer-deps, fix types

- packages/react-components/src/components/Dropdown/view.tsx
affects: `@findify/react-components`
> fix(@findify/react-components): Sort by icon should change when opening dropdown

- packages/config/src/Autocomplete.ts
- packages/react-components/src/layouts/Autocomplete/index.tsx
> moved autocomplete config to each template

- packages/react-components/src/layouts/Autocomplete/Dropdown/index.tsx
- packages/react-components/src/layouts/Autocomplete/Fullscreen/index.tsx
- packages/react-components/src/layouts/Autocomplete/Fullscreen/styles.css
> feat/DEV-1818: Fullscreen autocomplete

- packages/react-components/src/components/ColorFacet/Item.tsx
- packages/react-components/src/components/ColorFacet/content.tsx
- packages/react-components/src/components/ColorFacet/index.tsx
- packages/react-components/src/components/ColorFacet/styles.css
> feat/DEV-2145: Make default color palette on mobile bigger

- packages/config/src/enums.ts
> refactor(@findify/store-configuration): updated store status enum

- packages/config/src/enums.ts
> refactor(@findify/store-configuration): added rating facet type

- packages/config/src/Config.ts
> refactor(@findify/store-configuration): updated components type

- packages/bundle/src/config.ts
- packages/config/src/Autocomplete.ts
- packages/config/src/enums.ts
- packages/react-components/src/components/autocomplete/SearchSuggestions/index.tsx
- packages/react-components/src/components/autocomplete/SearchSuggestions/styles.css
- packages/react-components/src/layouts/Autocomplete/Dropdown/index.tsx
TODO: Add option to MD and admin API
> feat/DEV-1820: Horizontal suggestions

- packages/bundle/src/initialize.ts
BREAKING CHANGE: 7.0.0 release
<!--
> release 7.0.0

- packages/react-connect/src/connect/connectSuggestions.ts
> Minor fix release

- package.json
- packages/agent/README.md
- packages/analytics-dom/README.md
- packages/analytics/README.md
- packages/config/index.d.ts
- packages/config/package.json
- packages/react-components/index.d.ts
- packages/react-components/package.json
- packages/react-components/src/components/Cards/Product/Price/styles.css
- packages/react-components/src/components/autocomplete/SearchSuggestions/index.tsx
- packages/react-components/src/layouts/Autocomplete/withAutocompleteLogic.ts
- packages/sdk/README.md
- scripts/combineTypes.js
- yarn.lock
> Release major versions of packages

- packages/config/package.json
> Release 17.05.2021

- .gitignore
> chore(): do not push index.d.ts to git

- .circleci/config.yml
> chore(): update publishing config

- .gitignore
> chore(): remove types from git

- .gitignore
> fix(): remove types from ignore

- packages/agent/src/core/Agent.ts
- packages/sdk/src/index.ts
> feat(@findify/agent,@findify/sdk): bump major version

- packages/analytics-dom/src/index.ts
- packages/analytics/src/index.ts
> feat(@findify/analytics,@findify/analytics-dom): bump version

- packages/config/src/index.ts
> Release 19.05.2021

- packages/config/src/Autocomplete.ts
- packages/react-components/src/components/Breadcrumbs/createBreadcrumb.tsx
- packages/react-components/src/components/Facet/styles.css
- packages/react-components/src/components/autocomplete/ProductMatches/index.tsx
- packages/react-components/src/components/autocomplete/SearchSuggestions/index.tsx
- packages/react-components/src/components/search/DesktopFacets/index.tsx
- packages/react-components/src/helpers/chunks.ts
- packages/react-components/src/layouts/Autocomplete/Sidebar/index.tsx
- packages/react-components/src/layouts/Autocomplete/Sidebar/styles.css
- packages/react-components/src/layouts/Autocomplete/index.tsx
- packages/react-components/src/layouts/Autocomplete/types.ts
> Release 26.05.2021

- packages/config/src/Config.ts
- packages/react-components/src/components/Cards/Product/Price/index.tsx
- packages/react-components/src/components/Dropdown/styles.css
- packages/react-components/src/components/Facet/Component.ts
- packages/react-components/src/components/Facet/styles.css
- packages/react-components/src/components/common/Grid/styles.css
- packages/sdk/src/api.ts
- packages/sdk/src/utils.ts
> Release 01.06.2021

- packages/bundle/src/config.ts
- packages/react-components/src/components/Facet/styles.css
- packages/react-components/src/components/RangeFacet/styles.css
- packages/react-components/src/components/search/DesktopFacets/styles.css
> Release 03.06.2021

- packages/bundle/src/features/search/index.ts
- packages/react-components/src/layouts/ZeroResults/index.tsx
> fix(@findify/bundle,@findify/react-components): fix zeroResults view

- packages/bundle/src/config.ts
- packages/bundle/src/features/recommendation/payload.ts
- packages/react-components/src/components/Pagination/index.tsx
- packages/react-components/src/components/common/Image/index.tsx
- packages/react-components/src/components/common/Image/styles.css
> Release 06.07.2021

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
> Release 16.06.2021

- packages/analytics/README.md
> docs(@findify/analytics): update analytics documentation and reference urls

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/helpers/setupPlatforms.ts
> Release 23.06.2021

- packages/bundle/src/config.ts
- packages/react-components/src/components/Cards/Product/styles.css
- packages/react-components/src/components/Swiper/styles.css
- packages/react-components/src/components/Text/index.tsx
- packages/react-components/src/components/autocomplete/Tip/index.tsx
- packages/react-components/src/components/search/DesktopFacets/styles.css
- packages/react-components/src/layouts/Recommendation/Grid/index.tsx
- packages/react-components/src/layouts/Recommendation/Grid/styles.css
- packages/react-components/src/layouts/Recommendation/Slider/index.tsx
- packages/react-components/src/layouts/Recommendation/Slider/styles.css
- packages/react-components/src/layouts/ZeroResults/index.tsx
> Release 14.07.2021

- packages/react-components/src/components/ColorFacet/content.tsx
> fix(@findify/react-components): minor fix for color facets url value

- packages/react-components/package.json
> fix(@findify/react-components): fix components build sequence

- packages/react-components/src/helpers/chunks.ts
> fix(@findify/react-components): change dynamic import path for layouts

- packages/bundle/src/features/recommendation/payload.ts
- packages/config/src/Translations.ts
> Release 12.08.2021

- packages/react-components/src/components/search/LazyResults/index.tsx
- packages/react-components/src/components/search/LazyResults/styles.css
- packages/react-components/src/helpers/useLazy.ts
- packages/react-components/src/layouts/Recommendation/Grid/index.tsx
fix(@findify/react-components): fix grid template for recommendation & make lazy pagination crowable
<!--
> Release 16.08.2021

- packages/react-connect/src/connect/connectPagination.ts
> fix(@findify/react-connect): check if OOB while creating urls

- packages/react-components/src/components/Cards/Promo/index.tsx
- packages/react-components/src/components/Cards/Promo/styles.css
> fix(@findify/react-components): add promocard styling

- packages/bundle/src/core/location.ts
> fix(@findify/bundle): fix history update for SPA apps

- packages/bundle/src/core/location.ts
- packages/bundle/src/features/content/index.ts
> Release 28.09.21.01

- packages/bundle/src/features/recommendation/payload.ts
> Release 28.09.2021.2

- packages/bundle/src/config.ts
- packages/react-components/src/components/autocomplete/Products/index.tsx
> Release 06.10.21.01

- packages/react-components/src/components/Banner/index.tsx
> Release 02.11.21.01

- packages/react-components/src/components/Banner/index.tsx
- packages/react-components/src/layouts/ZeroResults/index.tsx
> fix(@findify/react-components): fixed lazy results text, updated banner  code to be cleaner

- packages/config/src/enums.ts
- packages/react-components/src/components/search/CombinedResults/index.tsx
- packages/react-components/src/components/search/LazyResults/index.tsx
- packages/react-components/src/components/search/SearchResultsLayout/index.tsx
- packages/react-components/src/layouts/Search/index.tsx
Allow merchant to add the Lazy results component in addition to the pagination option.
> feat(@findify/react-components): added CombinedResults component

- packages/bundle/src/core/location.ts
- packages/react-components/src/components/Cards/Product/index.tsx
- packages/react-components/src/components/search/CombinedResults/index.tsx
- packages/react-components/src/components/search/LazyResults/index.tsx
- packages/react-components/src/components/search/StaticResults/index.tsx
- packages/react-components/src/helpers/useScrollBackToProduct.ts
- packages/react-components/src/layouts/Search/index.tsx
- packages/react-connect/src/immutable/item.ts
1. Add product id to current URL hash when clicking on the product
2. Check if hash present in URL in product card and if it equals product ID scroll to this product
3. Remove hash from URL
> Fix 2996 scroll to product

- packages/bundle/src/helpers/scrollTo.ts
Do not scroll to top if hash presented in url
> fix(@findify/bundle): don't apply scroll to top if has hin url

- packages/bundle/src/core/widgets.ts
- packages/bundle/src/helpers/scrollTo.ts
- Fixed issue with undefined widgets
- Do not scroll if hash presented in url
> Release 02.12.21.02

- packages/bundle/src/config.ts
- packages/bundle/src/features/controlled-tabs/index.ts
- packages/config/src/Search.ts
> make content tabs optional

- packages/bundle/src/config.ts
- packages/bundle/src/features/controlled-tabs/index.ts
- packages/config/src/Search.ts
> updated controlled tabs

- packages/bundle/index.html
- packages/bundle/src/features/controlled-tabs/index.ts
> correctly hide loader in controlled tabs

- packages/bundle/src/config.ts
- packages/bundle/src/features/autocomplete/handlers.ts
- packages/bundle/src/features/search/index.ts
- packages/config/src/Autocomplete.ts
- packages/react-components/src/components/Cards/Product/Title/index.tsx
- packages/react-components/src/components/Cards/Product/index.tsx
- packages/react-components/src/helpers/useScrollBackToProduct.ts
- packages/react-components/src/layouts/Search/index.tsx
> Release 26.01.22

- packages/bundle/src/features/search/index.ts
> fix(@findify/bundle): render zero results on the next tick

- packages/bundle/src/initialize.ts
> fix(@findify/bundle): do not preload recommendations

- .circleci/config.yml
- packages/react-components/src/components/Swiper/loader.ts
- packages/react-components/src/helpers/chunks.ts
- packages/react-components/src/layouts/Content/index.tsx
> Release 03.02.22.01

- packages/react-components/src/components/Swiper/loader.ts
- packages/react-components/src/components/Swiper/raw.tsx
- packages/react-components/src/helpers/chunks.ts
> fix(@findify/react-components): fix

- packages/agent/src/core/Agent.ts
- packages/bundle/src/config.ts
> Release 18.03.22.01

- packages/react-connect/src/connect/createConnect.ts
> fix(@findify/react-connect): remove unecessary memoization

- packages/react-components/src/components/Cards/Product/index.tsx
- packages/react-components/src/components/common/Image/index.tsx
> fix(@findify/react-components): improved image lazy loading

- packages/bundle/src/core/location.ts
> Fix history by replacing history record rather than pushing new one

- packages/bundle/src/core/location.ts
> Fixed, do not change

- packages/bundle/src/core/location.ts
> Release 31.05.2022.1

- packages/react-components/src/components/search/DesktopFacets/index.tsx
> Filters are updated on navigation back and forward

- packages/react-components/src/components/search/DesktopFacets/index.tsx
> Release 06.06.2022

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
> Checking second parameter as fallback to check action POP

- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
> Release 24.06.2022.1

- packages/react-connect/src/immutable/facets.ts
> item-toggle check if not already within the state

- packages/bundle/src/initialize.ts
> Added message listener fro Chrome extension

- packages/react-components/src/layouts/Autocomplete/Sidebar/index.tsx
According to this issue: https://findify.atlassian.net/browse/DEV-4261
let's wait a little bit more before focusing input element
> Release 18.07.22.01

- packages/react-components/src/components/CheckboxFacet/index.tsx
> checkboxFacet for text filter uses .includes instead of Regex with gi

- packages/react-components/src/layouts/Autocomplete/Sidebar/index.tsx
> Release 20.07.2022

- packages/analytics/src/settings.ts
- packages/sdk/src/settings.ts
> Release 20.07.22.01

- packages/bundle/src/features/recommendation/payload.ts
> fix(@findify/bundle): always attach itemds to recommend request payload

- packages/bundle/src/initialize.ts
- packages/bundle/src/utils/inject.ts
> Refactored inject functions

- packages/analytics/src/index.ts
> Made it possible to control the input value of the view-page event

- packages/react-components/src/helpers/useScrollBackToProduct.ts
> wrap useScrollBackToProduct hook within try and catch

- packages/react-components/src/components/RatingFacet/content.tsx
> React-components - RatingFacet - Rating from double truncate it

- packages/react-components/src/helpers/useScrollBackToProduct.ts
> Release 26.09.2022

- packages/react-components/src/components/Cards/Product/index.tsx
- packages/react-components/src/helpers/useScrollBackToProduct.ts
- packages/react-components/src/layouts/Search/index.tsx
- packages/react-connect/src/immutable/item.ts
> Replace hash with localstorage ID to scroll back to producty

- packages/bundle/src/helpers/scrollTo.ts
> not maybescrolltop when pagination is combined

- packages/bundle/src/helpers/scrollTo.ts
> maybeScrollTop if not scolling back to product

- packages/bundle/src/helpers/scrollTo.ts
> Release 06.10.2022

- packages/bundle/src/core/location.ts
> Shopify multi_market flag redirection

- packages/bundle/src/core/location.ts
Multimarket flag and its redirections basepath logic update
<!--
> Release 14.11.2022

- packages/bundle/src/core/location.ts
> Multimarket getBasepath for redirection page

- packages/bundle/src/core/location.ts
> Release 14.11.2022.1

- packages/react-connect/src/immutable/content.ts
- packages/react-connect/src/immutable/item.ts
- packages/react-connect/src/utils/addBasepath.ts
> react-connect item and content should be aware of default path

- packages/bundle/src/core/location.ts
- packages/react-connect/src/immutable/content.ts
- packages/react-connect/src/immutable/item.ts
- packages/react-connect/src/utils/addBasepath.ts
> Release 14.11.2022.2

- packages/bundle/src/core/location.ts
Changes in isCollection and its collectionPath counterpart.
Made it more robust and reliable.
<!--
> isCollection function made more reliable

- packages/bundle/src/core/location.ts
- packages/react-components/src/components/CheckboxFacet/index.tsx
Retrocompatibility fix - 7.1.54 introduced issue
> Release 24.11.2022

- packages/react-components/src/components/CheckboxFacet/index.tsx
Retrocompatibility - second trial
> Release 24.11.2022.1

- packages/bundle/src/utils/inject.ts
> Injection function fix trial 1

- packages/bundle/src/utils/inject.ts
> Fix injection script

- packages/bundle/src/utils/inject.ts
DEV-4895 - MJS injection script, revert to older implementation fix
> Release 29.11.2022

- packages/bundle/src/utils/inject.ts
> Injection script eval fix

- packages/react-components/src/helpers/useLazy.ts
> Removed mistakenly and unused import

- packages/react-components/src/helpers/useLazy.ts
Removed unused and mistakenly imported library - no actual fix or new feature
> Release 07.12.2022.1

- packages/analytics/src/index.ts
> Analytics inverse condition

- .circleci/config.yml
- packages/analytics/README.md
- packages/bundle/src/config.ts
- packages/bundle/src/index.ts
- packages/cli/test/environment.js
Replaced CDN access to maxcdn to cloudfront
> Changed old CDN with anew cloudfront

- .circleci/config.yml
- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/analytics-dom/CHANGELOG.md
- packages/analytics-dom/package.json
- packages/analytics/CHANGELOG.md
- packages/analytics/package.json
- packages/bundle/CHANGELOG.md
- packages/bundle/package.json
- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/processors/CHANGELOG.md
- packages/processors/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/react-connect/CHANGELOG.md
- packages/react-connect/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
> Rotate circleci keys

- packages/analytics/src/modules/request.ts
> fix(@findify/analytics): re-added the key in the analytics api sending

- packages/analytics/src/modules/request.ts
> fix(@findify/analytics): fix url fetching for analytics

- packages/analytics/src/index.ts
- packages/bundle/src/core/location.ts
- packages/react-connect/src/utils/addBasepath.ts
> Check as well // to make regex more accurate

- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/recommendation/index.ts
> Hideloader wether items empty or not

- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/recommendation/index.ts
> Release 20.02.2023

- packages/react-components/src/components/Swiper/raw.tsx
- packages/react-components/src/components/Swiper/view.tsx
Swiper Autoplay module added and so, ready to be used
<!--
> Swiper Autoplay module added

- packages/analytics/src/settings.ts
- packages/react-components/src/layouts/ZeroResults/index.tsx
- packages/sdk/src/settings.ts
> Release 21.04.23

- packages/bundle/src/features/autocomplete/handlers.ts
> Autocomplete event handler open close fix

- packages/bundle/src/features/autocomplete/handlers.ts
> Add attribute for better selector handling

- packages/bundle/src/features/autocomplete/handlers.ts
Add attribute on autocomplete selector for better click handling
> Release 14.06.2023

- packages/bundle/src/core/location.ts
> Redirections multimarket, remove origin

- packages/bundle/src/core/location.ts
- packages/bundle/src/features/autocomplete/handlers.ts
Redirection for Shopify multimarket fixed
> Release 28.06.2023

- packages/react-components/src/components/Swiper/raw.tsx
- packages/react-components/src/components/Swiper/view.tsx
[DEV-5810](https://findify.atlassian.net/browse/DEV-5810)
[DEV-5810]: https://findify.atlassian.net/browse/DEV-5810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Scrollbar module added to swiper

- packages/bundle/src/core/location.ts
- packages/react-components/src/components/Swiper/raw.tsx
- packages/react-components/src/components/Swiper/view.tsx
[DEV-5810](https://findify.atlassian.net/browse/DEV-5810) - Added Scrollbar module to Swiper
[DEV-5810]: https://findify.atlassian.net/browse/DEV-5810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 28.06.2023.1

- packages/bundle/src/features/smart-collection/index.ts
> Sync with seach

- packages/analytics/src/index.ts
- packages/analytics/src/utils/location.ts
> Findev 180/analytics enrichment source and pagetype

- packages/bundle/src/features/content/index.ts
- packages/bundle/src/features/controlled-tabs/index.ts
- packages/bundle/src/features/recommendation/index.ts
- packages/bundle/src/features/search/index.ts
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/helpers/fallbackNode.ts
- packages/react-components/src/helpers/loader.ts
- packages/react-components/src/layouts/Content/index.tsx
- packages/react-components/src/layouts/Recommendation/Grid/index.tsx
- packages/react-components/src/layouts/Recommendation/Slider/index.tsx
- packages/react-components/src/layouts/Search/index.tsx
- packages/react-components/src/layouts/ZeroResults/index.tsx
> Hide loader moved within react-components

- packages/analytics/src/utils/location.ts
- packages/bundle/src/features/search/index.ts
> pageType analytics

- packages/react-components/src/components/search/CombinedResults/index.tsx
- packages/react-components/src/components/search/LazyResults/index.tsx
- packages/react-components/src/components/search/StaticResults/index.tsx
> set order for product cards to show promos in correct spots

- packages/analytics/src/index.ts
> pageType to page_type

- packages/analytics/src/index.ts
- packages/analytics/src/utils/location.ts
There was a collection as empty string. Don't know why BUT, I needed to nullcheck it.
<!--
> Analytics fix

- packages/analytics/src/index.ts
- packages/analytics/src/utils/location.ts
> Release 22.08.2023

- packages/react-components/src/helpers/useScrollBackToProduct.ts
> Remove product-id from localStorage within timeout

- packages/analytics-dom/CHANGELOG.md
- packages/analytics-dom/package.json
- packages/analytics/CHANGELOG.md
- packages/analytics/package.json
- packages/bundle/CHANGELOG.md
- packages/bundle/package.json
- packages/bundle/src/features/smart-collection/index.ts
- packages/bundle/src/helpers/fallbackNode.ts
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/react-connect/CHANGELOG.md
- packages/react-connect/package.json
> Findev 624 hideloader func is not working on collection with fallback

- packages/analytics/src/index.ts
> analytics user overwrite

- packages/analytics-dom/src/index.ts
- packages/analytics/src/index.ts
- packages/analytics/src/types.ts
- packages/analytics/src/utils/context.ts
- packages/bundle/src/config.ts
- packages/bundle/src/initialize.ts
- Added context and its methods to analytics SDK, configure locale, market, region
> Context for analytics

- packages/analytics/src/index.ts
> Removed console.log

- packages/agent/src/utils/format.ts
> filters fix for andrewsco

- packages/analytics/src/index.ts
> Release 13.03.2025

- packages/agent/src/utils/format.ts
> Release 24.04.2025

- packages/agent/CHANGELOG.md
- packages/agent/package.json
- packages/agent/src/utils/format.ts
- packages/analytics-dom/CHANGELOG.md
- packages/analytics-dom/package.json
- packages/analytics/CHANGELOG.md
- packages/analytics/package.json
- packages/bundle/CHANGELOG.md
- packages/bundle/package.json
- packages/config/CHANGELOG.md
- packages/config/package.json
- packages/processors/CHANGELOG.md
- packages/processors/package.json
- packages/react-components/CHANGELOG.md
- packages/react-components/package.json
- packages/react-connect/CHANGELOG.md
- packages/react-connect/package.json
- packages/sdk/CHANGELOG.md
- packages/sdk/package.json
> Revert branch for andrewsco

- packages/config/src/enums.ts
- packages/sdk/src/request/Recommendations.ts
> Recommendation type: Personalized
